### PR TITLE
Fix all the things!

### LINKED ISSUE #15: Cannot parse quantity-less rolls in expression
From @Lirusaito 

As I work on #13 I decided to look at the new dice regex, it appears it will not accept such expressions as `d10+3+d20+1d20`, the only expressions matched in this string will be the first `d10` and last `1d20` . The reason the first one is matched is because of the ^ beginning of string, subsequent quantityless rolls won't be at the beginning of the string, obviously, so they have to be matched some way else.

I could be wrong... it seems like only `d10+ d20` kinda thing will work, where there's a space before a die with quantity omission... that kinda breaks behavior.

### PR DESCRIPTION
**Pull request by LiruMouse**
...well, not really all of them, but it sounded like a good title. ^^;

Cleans up regex, fixes a warning in intellisense...
Adds a lenient regex option that fixes #15 for when Roll is called directly, and makes a bunch of functions relating to regex have a lenient option.
Removes parentheses from single die rolls, it always looked weird to me, only reason to have parentheses is to denote roll sections for the user and so the evaluator adds them preceding any other operation on them.
Adds #13 and #16.

### CODE REVIEW

**Comment by LiruMouse** [comment]
Huh, I've no idea why the Travis CI build failed... it said it built without error, and it works fine here, it looks like nunit is missing?

**Comment by cidthecoatrack** [comment]
The build says it failed because it couldn't load the nunit3 test runner.  I will check it out and see what is up.

**Comment by LiruMouse** [comment]
I've answered a few things you said, and what wasn't answered (and some of what was?) is now pushed.
Also I had a fix to add once I got this into the bot project I use this in, not sure why the tests succeeded when it failed in the bot, but either way its fixed now, so that's good.

**Comment by cidthecoatrack** [comment]
Awesome, thanks.  I will take a look at those changes.  On a somewhat-related note, have you gotten a chance to look into Uncle Bob yet?

**Comment by LiruMouse** [comment]
Only very briefly, between the pattern of my current social life and working on projects I'm spread a little thin.

**Comment by cidthecoatrack** [comment]
Trust me, I know the feeling. :)

**Comment by cidthecoatrack** [comment]
If you use a regular list (as my example does) within the method, but return the IEnumerable, then you really only worry about the list internally to the function - nothing outside would know or care that it was originally a list.  As for testing it, The easy thing is to get the individual rolls, verify a correct .Count(), and then verify a correct .Count() again.  With the `yield-return`, the first should pass, but the second would return 0.  If it is fixed, both will return the correct amount.

Also, sorry it took so long to respond - my schedule has been crazy lately

**Comment by cidthecoatrack** [comment]
Example:

``` csharp
[Test]
public void CanIterateOverRollsMultipleTimes()
{
    var count = 0;
    mockRandom.Setup(r => r.Next(90210)).Returns(() => count++);

    var rolls = dice.Roll(9266).IndividualRolls(90210);
    Assert.That(rolls.Count(), Is.EqualTo(9266));
    Assert.That(rolls, Is.Not.Empty);
    Assert.That(rolls.First(), Is.EqualTo(1));
    Assert.That(rolls.Last(), Is.EqualTo(9266));
    Assert.That(rolls.Count(), Is.EqualTo(9266));
}
```

There are more checks here than one would technically need to do (only the first two are absolutely needed), but extra asserts don't hurt anything. Feel free to use this as a template for your test.

**Comment by cidthecoatrack** [comment]
I rebased this off of the newest changes, so that the Trvis CI build will pass now

**Comment by LiruMouse** [comment]
This is so frustrating, I can't reproduce it in a test, but I can reliably
reproduce it in my bot.

**Comment by Lirusaito** [comment]
Okay so, stepping through this in the debugger with the current code you
pushed as Lirusaito-master
In
```cs
        private string CreateSumOfRolls(string roll)
```
When
```cs
var rolls = GetIndividualRolls(roll);
```
Executes, the call to IndividualRolls() gets skipped over.
THEN
When we reach
```cs
if (rolls.Any() == false)
```
My breakpoint in IndividualRolls() hits for the first time (therefore,
`quantity` gets lowered to 0 during this first call.)
Since this works as expected, rolls.Any() is true and we continue onto
```cs
var count = rolls.Count();
```
During this, my breakpoint in IndividualRolls() hits for a second time!!!
But, since my RandomPartialRoll object has already depleted `quantity` to
0, our yield loop will not execute, and we'll return an empty container.

To fix this, I'm going to do
```cs
var rolls = GetIndividualRolls(roll).ToList(); // or .ToArray()?
```
And that should solve this weird problem... we only want to execute
IndividualRolls() once, and that should do that.

**Comment by LiruMouse** [comment]
Okay so, stepping through this in the debugger with the current code you
pushed as Lirusaito-master
In

``` cs
        private string CreateSumOfRolls(string roll)
```

When

``` cs
var rolls = GetIndividualRolls(roll);
```

Executes, the call to IndividualRolls() gets skipped over.
THEN
When we reach

``` cs
if (rolls.Any() == false)
```

My breakpoint in IndividualRolls() hits for the first time (therefore,
`quantity` gets lowered to 0 during this first call.)
Since this works as expected, rolls.Any() is true and we continue onto

``` cs
var count = rolls.Count();
```

During this, my breakpoint in IndividualRolls() hits for a second time!!!
But, since my RandomPartialRoll object has already depleted `quantity` to
0, our yield loop will not execute, and we'll return an empty container.

To fix this, I'm going to do

``` cs
var rolls = GetIndividualRolls(roll).ToList(); // or .ToArray()?
```

And that should solve this weird problem... we only want to execute
IndividualRolls() once, and that should do that.

**Comment by cidthecoatrack** [comment]
Sounds good to me.  I personally prefer `ToArray()` to `ToList()`, but whichever you prefer is fine. :)  Once those are in and good, I'll do another review - and if everything looks kosher, I'll merge it in

**Comment by LiruMouse** [comment]
Array it is~

**Comment by cidthecoatrack** [comment]
So I had some time to look, and I have made some changes - mainly undoing the `yield-return` and using the list instead, returning the `IEnumerable<int>`.  I was also able to add an automated test verifying that we can iterate over the collection multiple times.  With the `yield-return`, the test fails, but using the `List<int>` internally, the test passes.  I did see the changes you pushed up with the `ToArray()`, but I feel odd about basically knowing that any time you call that method, you essentially HAVE to call that immediate functionality - which negates the whole delayed execution point of the `yield-return`

Again, considering the relatively small amount of data we are working with, I don't think we're going to see that big a gain between using the `yield-return` versus the `List<int>`.  Are you seeing differences in performance?

What are your thoughts on this changeset?

**Comment by cidthecoatrack** [comment]
My commit here: fdbd2f7fa856d9f5200647e1f9c6b667ce2064a1

**Comment by LiruMouse** [comment]
As I asked on that commit, is that stacked over my attempted fix? And I have no problem with your way, that's fine... I just need time to compile and test that in my bot project to say for certain (since I was seemingly never able to reproduce in a test, I'm slightly skeptical ^^;). But it looks fine to me.

**Comment by cidthecoatrack** [comment]
No, you're right - I somehow did not pull down your changes.  That was my bad.  I'll undo my changes, get a fresh checkout of your pull request, and give it another go :)

**Comment by cidthecoatrack** [comment]
Alright, I undid my changes, but I can't seem to find your new commits.  I hope I didn't overwrite them.  What were the SHAs of your changes?

**Comment by LiruMouse** [comment]
I overwrote them since you skipped over them... I still have it in a
branch.... 7ab77711d6c5f44732913aeaad49164866f147be
I tested your solution before pushing, by the way, it works fine... so it's
your call.

**Comment by cidthecoatrack** [comment]
Yeah, sorry about all this confusion.  I have been exceptionally scatterbrained.  I am having trouble checking out 7ab7771 - while it says that  68d8fc9 is its parent, I can't seem to check it out, cherry-pick it, find it with a fetch, anything.  Very confused.  I trust your code, I just want to be able to see it and run it locally, mainly to see if my test that I wrote does indeed verify the problem.

**Comment by LiruMouse** [comment]
Failed again?

**Comment by cidthecoatrack** [comment]
If you look through the commits, you'll see that 7ab7771 doesn't appear in the list - and ignore everything after 69d8fc9 . I deleted those commits.  Yes, they were all supposed to be built on top of your fix, but for some reason your fix doesn't show :disappointed:

**Comment by cidthecoatrack** [comment]
It's not as much that t failed - it's just that 7ab7771 doesn't show up in the commits, if you look at the alternate tab above.  It's also odd, because I've deleted the commits after 68d8fc9, since they were not valid - and yet they show up here as well.  GitHub might be doing something odd.  Can you just force-push your local branch with 7ab7771 so I can be sure to get those changes?

**Comment by LiruMouse** [comment]
But with them, my fix wasn't needed, since you hadn't merged my fix I just
retried on your branch and that worked so I pushed over my fix, hence it
not being in the list anymore. It's nothing odd, it's expected github
behavior, commits that are pushed are able to be accessed until an admin
(or a script) runs gc. We don't need that commit anymore.

**Comment by cidthecoatrack** [comment]
Well, in the current version of the pull request, I can make a test that verifies iterating over rolls multiple times, and that test fails, so your fix is indeed still needed.

**Comment by cidthecoatrack** [comment]
These changes have now been merge into master

**Pull request closed without merging**
