### PR TITLE
Packages update

### PR DESCRIPTION
**Pull request by LiruMouse**
Updates packages, including NUnit, and git ignores `*.log` files

### CODE REVIEW

**Comment by cidthecoatrack** [comment]
This is useful, thanks.  If you can actually merge this pr into the `develop` branch, then I can handle versioning and all that nitty-gritty housekeeping stuff and publish the updated packages to nuget.

It's also an opportunity to get rid of the RollGen/RollGen.Domain split (which is something I am pursuing in other projects for DnDGen as well)

**Comment by LiruMouse** [comment]
I'm a little confused on why you want this merged into the develop branch, as that branch is behind 4 commits.
image
I  can certainly do this, I'm just double checking that's what you want?

**Comment by LiruMouse** [comment]
There, I've picked the changes onto develop. Also, it looks like RollGen.Domain was already removed.

**Comment by cidthecoatrack** [comment]
Excellent, thank you.  I will make sure the master changes (just package tweaks) also get merged into develop

**Comment by cidthecoatrack** [comment]
So the target of this PR is still pointing toward master.  I have updated develop to include the master changes by rebasing - can you point this PR toward develop instead of master, please?

**Comment by LiruMouse** [comment]
There you go, my bad!

**Comment by cidthecoatrack** [comment]
Geez I am slow, and I'm sure all these wonderful updates are already old again. XD  Oh well, I'll merge it anyway!

**Pull request merged**
